window.YURUKAMI_CAMPAIGN = {
  meta: {
    campaignId: "yk_ningenkai_shingi_2026q3",
    name: "神々チャンネル 人間界審議",
    date: "2026-06-18",
    valueLine: "人間界のしんどい日常を、推し神が笑って裁いて、声つき神託で少し軽くする。",
    primaryPersona: "仕事・AI・人間関係の小さいストレスを抱え、推し活/デジタルグッズに抵抗がない20代後半から30代中心の視聴者",
  },
  paths: {
    chibiBase: "assets/characters/chibi/",
    normalBase: "assets/characters/normal/",
  },
  characters: [
    {
      id: "amaterasu",
      name: "アマテラス",
      shortName: "天照",
      role: "月曜朝の強制点灯係",
      color: "#E0492F",
      softColor: "#FBE3DD",
      chibi: "amaterasu.png",
      normal: "amaterasu.png",
      personaFit: ["AI・仕事疲れ", "コメント神託"],
      promise: "沈んだ気分を、勢いで昼に戻す。",
      fudaTitle: "強制点灯",
      fudaText: "今日は完璧でなくてよい。まず画面を一つ明るくする。",
      diagnosisLine: "あなたは、朝の気分を誰かに引き上げてほしい時期です。",
      ctaLabel: "月曜の神託を受け取る",
      shopLead: "月曜朝の待受、会議前ボイス、勢い返信札に向く推し神。",
    },
    {
      id: "konohana",
      name: "コノハナサクヤ",
      shortName: "コノハナ",
      role: "荒れた感情の整え役",
      color: "#D96A8B",
      softColor: "#FCEFF3",
      chibi: "konohana.png",
      normal: "konohana.png",
      personaFit: ["仕事疲れ", "推し活ライト"],
      promise: "言いすぎそうな気持ちを、きれいに言い直す。",
      fudaTitle: "言い直し",
      fudaText: "刺さる言葉は、少し花びらに包んでから渡す。",
      diagnosisLine: "あなたは、感情を消すより整えたいタイプです。",
      ctaLabel: "言い直し神札を受け取る",
      shopLead: "返信文、壁紙、やさしい一言ボイスに強い推し神。",
    },
    {
      id: "ameno_uzume",
      name: "アメノウズメ",
      shortName: "ウズメ",
      role: "空気の詰まりを破る踊り手",
      color: "#F0907D",
      softColor: "#FCEFEA",
      chibi: "ameno_uzume.png",
      normal: "amenouzume.png",
      personaFit: ["人間関係", "コメント神託"],
      promise: "気まずさを、笑って動かす。",
      fudaTitle: "場を動かす",
      fudaText: "沈黙は敵ではない。最初の一言だけ、軽く置く。",
      diagnosisLine: "あなたは、空気を読みすぎて止まる場面が増えています。",
      ctaLabel: "空気を動かす札を見る",
      shopLead: "会話開始スタンプ、短い応援ボイス、飲み会前の神託に向く。",
    },
    {
      id: "tagitsuhime",
      name: "タギツヒメ",
      shortName: "タギツ",
      role: "通知の濁流を仕分ける水神",
      color: "#3E96AD",
      softColor: "#EAF6F9",
      chibi: "tagitsuhime.png",
      normal: "tagitsuhime.png",
      personaFit: ["AI・仕事疲れ", "通知疲れ"],
      promise: "流れすぎる情報を、今日見るものだけに分ける。",
      fudaTitle: "濁流仕分け",
      fudaText: "全部は拾わない。岸に寄せるものを三つだけ決める。",
      diagnosisLine: "あなたは、情報量ではなく流速に疲れています。",
      ctaLabel: "通知仕分け札を受け取る",
      shopLead: "タスク整理、通知疲れ、情報収集の壁紙/ボイスに向く。",
    },
    {
      id: "ototachibana",
      name: "オトタチバナ",
      shortName: "橘",
      role: "言えない本音の波止場",
      color: "#7CC5D6",
      softColor: "#D6EEF4",
      chibi: "ototachibana.png",
      normal: "ototachibana.png",
      personaFit: ["人間関係", "ライト占い"],
      promise: "飲み込んだ言葉を、静かにほどく。",
      fudaTitle: "本音の波止場",
      fudaText: "言わない優しさと、言う必要は別の舟に乗せる。",
      diagnosisLine: "あなたは、自分だけが我慢すれば済むと思いがちです。",
      ctaLabel: "本音をほどく札を見る",
      shopLead: "夜の神託、静かな壁紙、長めの癒やしボイスに向く。",
    },
    {
      id: "yamatotakeru",
      name: "ヤマトタケル",
      shortName: "タケル",
      role: "タスクを斬る決断係",
      color: "#B53A24",
      softColor: "#FBE3DD",
      chibi: "yamatotakeru.png",
      normal: "yamatotakeru.png",
      personaFit: ["仕事疲れ", "先延ばし"],
      promise: "迷いを短くして、一手目を決める。",
      fudaTitle: "一手断ち",
      fudaText: "全部を倒すな。最初の敵だけ名前で呼べ。",
      diagnosisLine: "あなたは、やる気より着手の形が足りない状態です。",
      ctaLabel: "一手目の神託を受け取る",
      shopLead: "タスク着手、締切前、朝活ボイスに向く推し神。",
    },
    {
      id: "kikurihime",
      name: "キクリヒメ",
      shortName: "キクリ",
      role: "こじれた会話の結び直し",
      color: "#9183C9",
      softColor: "#EEEAF8",
      chibi: "kikurihime.png",
      normal: "kikurihime.png",
      personaFit: ["人間関係", "推し活ライト"],
      promise: "ほどけた関係を、無理なく結び直す。",
      fudaTitle: "結び直し",
      fudaText: "正しさだけで結ぶと、すぐほどける。余白も一緒に結ぶ。",
      diagnosisLine: "あなたは、勝つ会話より戻れる会話を必要としています。",
      ctaLabel: "結び直し神札を受け取る",
      shopLead: "関係修復、DM返信、静かな励ましボイスに向く。",
    },
    {
      id: "toyotamahime",
      name: "トヨタマヒメ",
      shortName: "豊玉",
      role: "深夜の情緒を沈める海神",
      color: "#6B5BA8",
      softColor: "#EEEAF8",
      chibi: "toyotamahime.png",
      normal: "toyotamahime.png",
      personaFit: ["夜の反省会", "推し活ライト"],
      promise: "夜に大きく見える不安を、朝まで預かる。",
      fudaTitle: "深夜預かり",
      fudaText: "深夜の結論は、海に沈めて朝に拾う。",
      diagnosisLine: "あなたは、夜だけ強くなる考えに引っぱられています。",
      ctaLabel: "深夜預かり札を見る",
      shopLead: "睡眠前ボイス、夜用壁紙、情緒鎮めカードに向く。",
    },
  ],
  diagnosis: {
    questions: [
      {
        id: "stress_source",
        text: "いま一番、神々に審議してほしい人間界の問題は？",
        choices: [
          { label: "AIと仕事チャット", weights: { tagitsuhime: 3, amaterasu: 2, yamatotakeru: 1 } },
          { label: "上司・会議・締切", weights: { yamatotakeru: 3, amaterasu: 2, konohana: 1 } },
          { label: "人間関係の言い方", weights: { kikurihime: 3, konohana: 2, ototachibana: 1 } },
          { label: "夜の反省会", weights: { toyotamahime: 3, ototachibana: 2, kikurihime: 1 } },
        ],
      },
      {
        id: "desired_response",
        text: "返ってきてほしい神託の温度は？",
        choices: [
          { label: "勢いで背中を押してほしい", weights: { amaterasu: 3, yamatotakeru: 2, ameno_uzume: 1 } },
          { label: "きれいに言い換えてほしい", weights: { konohana: 3, kikurihime: 2, ototachibana: 1 } },
          { label: "笑って場を動かしてほしい", weights: { ameno_uzume: 3, amaterasu: 1, tagitsuhime: 1 } },
          { label: "静かに預かってほしい", weights: { toyotamahime: 3, ototachibana: 2, kikurihime: 1 } },
        ],
      },
      {
        id: "share_scene",
        text: "神札を使うなら、どの場面が近い？",
        choices: [
          { label: "月曜朝の待受", weights: { amaterasu: 3, yamatotakeru: 2 } },
          { label: "友だちへの返信", weights: { ameno_uzume: 3, konohana: 2, kikurihime: 1 } },
          { label: "仕事前の一言", weights: { yamatotakeru: 3, tagitsuhime: 2, amaterasu: 1 } },
          { label: "寝る前の保存用", weights: { toyotamahime: 3, ototachibana: 2 } },
        ],
      },
      {
        id: "purchase_motive",
        text: "お金を払うなら、何が一番うれしい？",
        choices: [
          { label: "自分の投稿が審議される", weights: { amaterasu: 2, ameno_uzume: 2, tagitsuhime: 1 } },
          { label: "推し神の壁紙や神札を集める", weights: { konohana: 2, toyotamahime: 2, kikurihime: 2 } },
          { label: "声つきの短い神託が届く", weights: { ototachibana: 2, toyotamahime: 2, amaterasu: 1 } },
          { label: "仕事や返信に使える定型札", weights: { tagitsuhime: 2, yamatotakeru: 2, konohana: 1 } },
        ],
      },
      {
        id: "tone_guardrail",
        text: "苦手なノリはどれ？",
        choices: [
          { label: "スピリチュアルすぎる", weights: { yamatotakeru: 2, tagitsuhime: 2, ameno_uzume: 1 } },
          { label: "説明が長い", weights: { amaterasu: 2, ameno_uzume: 2, yamatotakeru: 1 } },
          { label: "強く言われすぎる", weights: { konohana: 2, kikurihime: 2, ototachibana: 1 } },
          { label: "軽すぎて刺さらない", weights: { toyotamahime: 2, ototachibana: 2, kikurihime: 1 } },
        ],
      },
    ],
  },
  products: [
    {
      tier: "free",
      name: "無料 推し神診断 + 神札8枚",
      price: 0,
      role: "Shortsからowned fan化する入口",
      promise: "診断結果と保存用の神札をすぐ渡す。",
      cta: "無料神札を受け取る",
      kpi: "LP visit to owned fan conversion 25%",
    },
    {
      tier: "entry",
      name: "神札スターターパック beta",
      price: 500,
      role: "購入意向テスト",
      promise: "8神のスマホ壁紙、返信用カード、タギツヒメのタイパ仕分け札をまとめる。",
      cta: "商品化希望を送る",
      kpi: "LP product_interest 5%",
    },
    {
      tier: "core",
      name: "FANBOX 月例 人間界審議",
      price: 1000,
      role: "継続課金",
      promise: "月2回の会員投稿審議、先行神札、制作メモを出す。",
      cta: "月例審議に参加する",
      kpi: "owned fan to paid supporter 3.5%",
    },
    {
      tier: "premium",
      name: "個別ミニ神託",
      price: 4000,
      role: "高単価テスト",
      promise: "投稿された悩みを1件、推し神の短文神託とカード案にする。",
      cta: "個別神託の枠を見る",
      kpi: "50 slots per month after audience validation",
    },
    {
      tier: "event",
      name: "推し神投票 追加ボイス月",
      price: 0,
      role: "参加率と再訪を上げるイベント",
      promise: "次に作る声・神札・Shorts題材を投票で決める。",
      cta: "次の審議に投票する",
      kpi: "owned fan monthly active rate 20%",
    },
  ],
  funnelTargets: {
    viewToVisit: { conservative: 0.002, target: 0.005, aggressive: 0.008 },
    visitToOwned: { conservative: 0.15, target: 0.25, aggressive: 0.35 },
    ownedToPaid: { conservative: 0.02, target: 0.035, aggressive: 0.05 },
    ownedToBooth: { conservative: 0.01, target: 0.02, aggressive: 0.04 },
    fanboxNetArppu: { conservative: 810, target: 990, aggressive: 1260 },
    boothNetPerBuyer: 1371,
    monthlyOwnedFanGoal: 20000,
    monthlyPaidGoal: 750,
    monthlyNetRevenueGoal: 1000000,
  },
  shortSeries: [
    {
      id: "ai_thanks_001",
      series: "AIあるある審議",
      title: "AIにありがとうって言う派、神々が審議",
      persona: "P1",
      primaryCharacter: "amaterasu",
      hook: "AIに毎回ありがとうって言うの、必要ですか。",
      beats: [
        "アマテラスが、礼を尽くす派として強く出る。",
        "タギツヒメが、仕事の流速が上がるなら短くていいと整理する。",
        "コノハナが、ありがとうは相手より自分の言葉づかいを守る札だとまとめる。",
        "神託: 言ってもよし。ただし締切前は一礼で去れ。",
      ],
      cta: "あなたはAIに礼を言う派か、コメントで審議提出。",
      kpiHypothesis: "comment_rate_target_0.25%",
    },
    {
      id: "ai_prompt_polite_002",
      series: "AIあるある審議",
      title: "プロンプトを丁寧語にする派",
      persona: "P1",
      primaryCharacter: "konohana",
      hook: "AIへの依頼文だけ、なぜか社会人メールになる。",
      beats: [
        "コノハナが、言葉の型があると自分の目的も整うと肯定する。",
        "アメノウズメが、最後に何卒を付けた時点で人間の負けと茶化す。",
        "ヤマトタケルが、目的、条件、出力だけ斬り出せと短くする。",
        "神託: 丁寧でもよし。遠回しな依頼は黄泉送り。",
      ],
      cta: "あなたのAI依頼文を神々に見せるなら、どこを直すか。",
      kpiHypothesis: "save_rate_target_0.35%",
    },
    {
      id: "ai_tab_overflow_003",
      series: "AIあるある審議",
      title: "AIタブを開きすぎて逆に迷う",
      persona: "P1",
      primaryCharacter: "tagitsuhime",
      hook: "AIを使うほど、タブが増えて人間が遅くなる問題。",
      beats: [
        "タギツヒメが、情報の川幅を広げすぎたと診断する。",
        "アマテラスが、全部見れば勝てると言って溺れかける。",
        "キクリヒメが、今日使うタブと未来の不安タブを結び分ける。",
        "神託: 開く前に閉じる数を決めよ。",
      ],
      cta: "いま開いているAIタブ数をコメントで自己申告。",
      kpiHypothesis: "comment_rate_target_0.20%",
    },
    {
      id: "ai_output_sorry_004",
      series: "AIあるある審議",
      title: "AIの謝罪文にこちらが気を使う",
      persona: "P1",
      primaryCharacter: "ototachibana",
      hook: "AIが謝るたびに、こっちが悪い気がしてくる。",
      beats: [
        "オトタチバナが、謝罪を受け取りすぎる人間の癖を拾う。",
        "アメノウズメが、機械にまで気まずくなるのは才能と笑う。",
        "コノハナが、修正依頼は責めではなく道案内だと整える。",
        "神託: その謝罪、保存せず次の条件を渡せ。",
      ],
      cta: "AIに気を使った経験を審議に出す。",
      kpiHypothesis: "owned_click_target_0.55%",
    },
    {
      id: "work_take_back_005",
      series: "仕事の黄泉審議",
      title: "一旦持ち帰りますは黄泉か",
      persona: "P1",
      primaryCharacter: "yamatotakeru",
      hook: "会議の『一旦持ち帰ります』、どこへ持ち帰っているのか。",
      beats: [
        "ヤマトタケルが、持ち帰り先を明記せよと斬り込む。",
        "アマテラスが、だいたい机の端で眠ると断言する。",
        "キクリヒメが、期限と次の一手を結ばない言葉はほどけると整理する。",
        "神託: 持ち帰るなら、帰着時刻も添えよ。",
      ],
      cta: "あなたの職場の黄泉ワードをコメントへ。",
      kpiHypothesis: "comment_rate_target_0.30%",
    },
    {
      id: "work_calendar_006",
      series: "仕事の黄泉審議",
      title: "15分会議が30分になる罪",
      persona: "P1",
      primaryCharacter: "tagitsuhime",
      hook: "15分会議が30分になる現象、神罰の対象ですか。",
      beats: [
        "タギツヒメが、時間の堤防が決壊していると見る。",
        "アメノウズメが、最後の雑談こそ本体説を出す。",
        "ヤマトタケルが、決めること一つ、捨てる話二つと裁く。",
        "神託: 15分会議は、終わり方から決めよ。",
      ],
      cta: "伸びる会議あるあるを審議提出。",
      kpiHypothesis: "retention_target_72%",
    },
    {
      id: "work_unread_007",
      series: "仕事の黄泉審議",
      title: "未読が増えるほど返せなくなる",
      persona: "P1",
      primaryCharacter: "kikurihime",
      hook: "未読が3件を超えた瞬間、返信の神が消える。",
      beats: [
        "キクリヒメが、未読は数ではなく関係の重さになると読む。",
        "アマテラスが、全部『見ました』で燃やそうとする。",
        "コノハナが、一番軽い返信から結び直す案を出す。",
        "神託: 返事は完璧より先着一通。",
      ],
      cta: "未読を何件ためたら動けなくなるか投票。",
      kpiHypothesis: "poll_click_target_1.0%",
    },
    {
      id: "work_monday_008",
      series: "仕事の黄泉審議",
      title: "月曜朝の体感重力",
      persona: "P1",
      primaryCharacter: "amaterasu",
      hook: "月曜朝だけ、布団の重力が別料金になる。",
      beats: [
        "アマテラスが、太陽側にも起動コストがあると主張する。",
        "トヨタマヒメが、日曜夜の結論を朝に持ち込むなと静める。",
        "ヤマトタケルが、一手目を水、顔、靴の三択に絞る。",
        "神託: 月曜は人生を始めず、靴だけ履け。",
      ],
      cta: "月曜朝の神札を診断ページで配布中。",
      kpiHypothesis: "lp_click_target_0.7%",
    },
    {
      id: "work_cc_009",
      series: "仕事の黄泉審議",
      title: "CCに入っただけで心拍が上がる",
      persona: "P1",
      primaryCharacter: "ototachibana",
      hook: "CCに名前があるだけで、なぜか審判席に座らされる。",
      beats: [
        "オトタチバナが、見守りと責任の境界が曖昧だと拾う。",
        "タギツヒメが、通知の川に石を投げるなと整理する。",
        "アメノウズメが、CCは神々の観覧席と茶化す。",
        "神託: 呼ばれていない裁判には、静かに座れ。",
      ],
      cta: "職場メールの小罪を募集。",
      kpiHypothesis: "comment_rate_target_0.20%",
    },
    {
      id: "work_deadline_010",
      series: "仕事の黄泉審議",
      title: "締切直前だけ急に掃除したくなる",
      persona: "P1",
      primaryCharacter: "yamatotakeru",
      hook: "締切前の机掃除、あれは祈りか逃避か。",
      beats: [
        "ヤマトタケルが、逃げ道に名前をつけた時点で半分勝ちとする。",
        "コノハナが、机ではなく最初の一文を整えよと言う。",
        "アマテラスが、掃除で太陽が入るなら少し許すと揺れる。",
        "神託: 掃除は5分。本文は1行。",
      ],
      cta: "先延ばしの儀式をコメントで審議。",
      kpiHypothesis: "save_rate_target_0.40%",
    },
    {
      id: "human_reply_011",
      series: "人間関係の小罪審議",
      title: "了解だけだと冷たい問題",
      persona: "P2",
      primaryCharacter: "konohana",
      hook: "『了解』だけ送ると冷たい気がする人、集合。",
      beats: [
        "コノハナが、一語でも温度は調整できると示す。",
        "キクリヒメが、相手との結び目によって言葉は変わると整理する。",
        "アメノウズメが、『了解です、助かります』を万能札にする。",
        "神託: 了解に一滴だけ体温を足せ。",
      ],
      cta: "返信を整える推し神診断へ。",
      kpiHypothesis: "lp_click_target_0.8%",
    },
    {
      id: "human_seen_012",
      series: "人間関係の小罪審議",
      title: "既読をつけた瞬間に追われる",
      persona: "P2",
      primaryCharacter: "kikurihime",
      hook: "既読は返事ではないのに、心は出廷する。",
      beats: [
        "キクリヒメが、既読と返事を同じ紐で結ぶから苦しいと見る。",
        "オトタチバナが、返せない時間にも理由はあると受ける。",
        "ヤマトタケルが、返す時刻だけ決めて斬る。",
        "神託: 既読は入室。発言は別の札。",
      ],
      cta: "既読の小罪を審議提出。",
      kpiHypothesis: "comment_rate_target_0.22%",
    },
    {
      id: "human_groupchat_013",
      series: "人間関係の小罪審議",
      title: "グループチャットの最後を誰が締めるか",
      persona: "P2",
      primaryCharacter: "ameno_uzume",
      hook: "グループチャット、最後のスタンプ係が毎回同じ。",
      beats: [
        "アメノウズメが、場を閉じる人は小さな舞をしていると表現する。",
        "コノハナが、締めの言葉は関係の掃除だと整える。",
        "アマテラスが、既読全員に拍手を求めて止められる。",
        "神託: 最後の一言は、義務ではなく戸締まり。",
      ],
      cta: "あなたの締めスタンプ役を推し神診断へ。",
      kpiHypothesis: "share_rate_target_0.15%",
    },
    {
      id: "human_apology_014",
      series: "人間関係の小罪審議",
      title: "謝りすぎて逆に重い問題",
      persona: "P2",
      primaryCharacter: "ototachibana",
      hook: "すみませんを重ねすぎて、荷物が増える時がある。",
      beats: [
        "オトタチバナが、謝罪で自分を沈めすぎていると見る。",
        "コノハナが、謝罪、状況、次の行動に分ける。",
        "アメノウズメが、すみません五連打を神域で止める。",
        "神託: 謝るなら一度、直すなら具体的に。",
      ],
      cta: "言い直し神札を無料で保存。",
      kpiHypothesis: "lp_click_target_0.6%",
    },
    {
      id: "human_invite_015",
      series: "人間関係の小罪審議",
      title: "誘いを断る文面が一番むずかしい",
      persona: "P2",
      primaryCharacter: "konohana",
      hook: "予定を断るだけなのに、文章が謝罪会見になる。",
      beats: [
        "コノハナが、断る理由を盛りすぎると花が折れると諭す。",
        "キクリヒメが、また会える余白を結んでおけばいいと言う。",
        "ヤマトタケルが、行けない、ありがとう、また今度の三手で斬る。",
        "神託: 断る文は短く、縁は残す。",
      ],
      cta: "断り文の神札が必要なら診断へ。",
      kpiHypothesis: "save_rate_target_0.45%",
    },
    {
      id: "night_regret_016",
      series: "夜の反省会審議",
      title: "寝る前に会話を再生してしまう",
      persona: "P2",
      primaryCharacter: "toyotamahime",
      hook: "寝る前だけ、昼の一言が劇場公開される。",
      beats: [
        "トヨタマヒメが、夜の海は音を大きく返すと見る。",
        "オトタチバナが、その時の自分も必死だったと受け止める。",
        "キクリヒメが、明日直せる結び目だけ残す。",
        "神託: 深夜の反省は下書き保存。",
      ],
      cta: "深夜預かり札を受け取る。",
      kpiHypothesis: "owned_click_target_0.65%",
    },
    {
      id: "night_future_017",
      series: "夜の反省会審議",
      title: "未来の不安を夜に前借りする罪",
      persona: "P2",
      primaryCharacter: "toyotamahime",
      hook: "まだ起きていない問題で、なぜか今日疲れる。",
      beats: [
        "トヨタマヒメが、未来の波を今の岸に呼びすぎていると見る。",
        "タギツヒメが、今日処理できる水量だけに分ける。",
        "アマテラスが、朝の自分に少し返せと明るく裁く。",
        "神託: 明日の不安は、明日の神域に置け。",
      ],
      cta: "夜用神札を保存して朝に見る。",
      kpiHypothesis: "save_rate_target_0.50%",
    },
    {
      id: "diagnosis_push_018",
      series: "推し神診断",
      title: "あなたの仕事疲れに付く神は誰か",
      persona: "P1/P2",
      primaryCharacter: "amaterasu",
      hook: "仕事疲れの種類で、付く神が変わります。",
      beats: [
        "アマテラスが、朝起きられない疲れ担当として出る。",
        "タギツヒメが、通知に流される疲れを担当する。",
        "コノハナが、言葉づかいで消耗する疲れを担当する。",
        "神託: 診断で、今の推し神を一体選べ。",
      ],
      cta: "推し神診断は概要欄から。",
      kpiHypothesis: "lp_click_target_1.0%",
    },
    {
      id: "diagnosis_voice_019",
      series: "推し神診断",
      title: "神託は文字より声で刺さる説",
      persona: "P2",
      primaryCharacter: "ototachibana",
      hook: "同じ言葉でも、推し神の声だと逃げられない。",
      beats: [
        "オトタチバナが、声は言葉の温度を運ぶと話す。",
        "アメノウズメが、通知音だけで背筋が伸びると笑う。",
        "キクリヒメが、会員向け月例神託への導線を自然に置く。",
        "神託: 文字で残し、声で届かせよ。",
      ],
      cta: "声つき神託の先行案内に登録。",
      kpiHypothesis: "owned_conversion_target_30%",
    },
    {
      id: "diagnosis_fuda_020",
      series: "推し神診断",
      title: "保存される神札の条件",
      persona: "P2",
      primaryCharacter: "konohana",
      hook: "神札は、きれいな絵より使える一言で保存される。",
      beats: [
        "コノハナが、保存される言葉は今日の場面を持つと整理する。",
        "アマテラスが、勢いだけの札を量産しかける。",
        "タギツヒメが、用途別に月曜、返信、深夜へ分ける。",
        "神託: 飾る札より、使う札を作れ。",
      ],
      cta: "無料神札8枚を診断ページで配布。",
      kpiHypothesis: "lp_click_target_0.9%",
    },
    {
      id: "comment_trial_021",
      series: "コメント神託",
      title: "視聴者の『朝起きられない』を審議",
      persona: "P1",
      primaryCharacter: "amaterasu",
      hook: "朝起きられない罪、太陽神が被告側に立ちます。",
      beats: [
        "アマテラスが、自分も毎朝点灯しているので偉いと主張する。",
        "トヨタマヒメが、夜の過ごし方を審議に入れる。",
        "ヤマトタケルが、起床ではなく着席までを一手にする。",
        "神託: 起きるな。まず座れ。",
      ],
      cta: "あなたの小罪もコメントで提出。",
      kpiHypothesis: "comment_rate_target_0.35%",
    },
    {
      id: "comment_trial_022",
      series: "コメント神託",
      title: "視聴者の『返信が遅い』を審議",
      persona: "P2",
      primaryCharacter: "kikurihime",
      hook: "返信が遅い人は、縁を切っているのか守っているのか。",
      beats: [
        "キクリヒメが、遅い返信にも戻る道があると見る。",
        "コノハナが、短い現状報告だけで関係は保てると整える。",
        "アメノウズメが、三日後の『ごめん寝てた』を舞で止める。",
        "神託: 返せない時こそ、短く橋を架けよ。",
      ],
      cta: "返信神札を無料で保存。",
      kpiHypothesis: "lp_click_target_0.7%",
    },
    {
      id: "comment_trial_023",
      series: "コメント神託",
      title: "視聴者の『買った本を積む』を審議",
      persona: "P2",
      primaryCharacter: "toyotamahime",
      hook: "積んだ本は罪ですか、それとも未来の神棚ですか。",
      beats: [
        "トヨタマヒメが、読めない夜にも本は灯台になると見る。",
        "ヤマトタケルが、最初の3ページだけ斬れと命じる。",
        "アメノウズメが、積む高さで信仰心を測ろうとして止められる。",
        "神託: 一冊を倒さず、一頁を開け。",
      ],
      cta: "あなたの積み罪を提出。",
      kpiHypothesis: "comment_rate_target_0.25%",
    },
    {
      id: "sticker_use_024",
      series: "使える神札",
      title: "『了解です』の代わりになる神札",
      persona: "P2",
      primaryCharacter: "konohana",
      hook: "了解です、だけで冷たくしたくない人の神札。",
      beats: [
        "コノハナが、短い返信に花びら一枚の温度を足す。",
        "キクリヒメが、相手との距離ごとに札を分ける。",
        "アメノウズメが、使いすぎると神託botになると釘を刺す。",
        "神託: 了解に、助かりますを添えて渡せ。",
      ],
      cta: "返信用神札パックの先行案内へ。",
      kpiHypothesis: "owned_conversion_target_28%",
    },
    {
      id: "sticker_use_025",
      series: "使える神札",
      title: "締切前に貼る神札",
      persona: "P1",
      primaryCharacter: "yamatotakeru",
      hook: "締切前に必要なのは気合いではなく、一手目です。",
      beats: [
        "ヤマトタケルが、気合いを信用しすぎるなと裁く。",
        "タギツヒメが、タスクを今日の水量に分ける。",
        "アマテラスが、最初の一手を照らして終わる。",
        "神託: やる気待ちは却下。ファイルを開け。",
      ],
      cta: "一手断ち神札を無料で保存。",
      kpiHypothesis: "save_rate_target_0.45%",
    },
    {
      id: "sticker_use_026",
      series: "使える神札",
      title: "通知を切る罪を無罪にする札",
      persona: "P1",
      primaryCharacter: "tagitsuhime",
      hook: "通知を切るのは逃げか、治水か。",
      beats: [
        "タギツヒメが、通知を全部受けるのは治水放棄と裁く。",
        "アマテラスが、全部見る派として燃え尽きる。",
        "コノハナが、返信可能時間を先に伝えれば角が立たないと整える。",
        "神託: 通知を切るなら、戻る時刻を決めよ。",
      ],
      cta: "通知仕分け札を診断で受け取る。",
      kpiHypothesis: "lp_click_target_0.75%",
    },
    {
      id: "fan_vote_027",
      series: "推し神投票",
      title: "次に声を増やす神、誰にするか",
      persona: "P2/P3",
      primaryCharacter: "ameno_uzume",
      hook: "次の声つき神託、誰から増やすか神々が揉めています。",
      beats: [
        "アメノウズメが、自分の場を動かす声を推す。",
        "オトタチバナが、夜用の静かな声も必要と返す。",
        "アマテラスが、投票で決めれば太陽的に公平と押す。",
        "神託: 次の声は、人間界の票で決める。",
      ],
      cta: "推し神投票は診断ページから。",
      kpiHypothesis: "owned_active_target_20%",
    },
    {
      id: "making_of_028",
      series: "制作裏側",
      title: "神々の声を作り分ける時に見ていること",
      persona: "P3",
      primaryCharacter: "kikurihime",
      hook: "同じ台詞でも、神が違うと必要な間が違います。",
      beats: [
        "キクリヒメが、声は高さより言葉の待ち方だと説明する。",
        "アマテラスが、勢いの声は短文で光ると見せる。",
        "トヨタマヒメが、夜用の声は沈黙を削りすぎないと示す。",
        "神託: 声はキャラ設定ではなく、場面で決まる。",
      ],
      cta: "制作メモはFANBOX準備中。",
      kpiHypothesis: "p3_click_target_0.8%",
    },
    {
      id: "making_of_029",
      series: "制作裏側",
      title: "AI画像をIP資産にする時の罠",
      persona: "P3",
      primaryCharacter: "konohana",
      hook: "きれいな一枚絵だけでは、キャラは商品になりません。",
      beats: [
        "コノハナが、使う場面ごとに表情、神札、声が必要と整理する。",
        "タギツヒメが、管理できない差分は濁流になると警告する。",
        "アメノウズメが、かわいいだけで進めると後で踊れないと笑う。",
        "神託: IPは絵ではなく、繰り返し使える約束。",
      ],
      cta: "制作裏側の希望者は登録へ。",
      kpiHypothesis: "owned_conversion_target_20%",
    },
    {
      id: "launch_offer_030",
      series: "ローンチ告知",
      title: "無料神札8枚、先に配ります",
      persona: "P1/P2",
      primaryCharacter: "amaterasu",
      hook: "神々チャンネル、人間界審議を始めます。",
      beats: [
        "アマテラスが、仕事疲れも返信疲れも神域に持って来いと宣言する。",
        "コノハナが、最初は診断と無料神札8枚から始めると整理する。",
        "キクリヒメが、コメントを次の審議題に結ぶと約束する。",
        "神託: まず推し神を決めよ。審議はそこから始まる。",
      ],
      cta: "概要欄から推し神診断へ。",
      kpiHypothesis: "lp_click_target_1.2%",
    },
  ],
};
